apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    app: frontend
