apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-repository
  name: mongodb-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-repository
  template:
    metadata:
      labels:
        app: mongodb-repository
    spec:
      containers:
      - image: bricov/speech_repository
        name: mongodb-repository
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
